# Generated by Django 5.1.2 on 2024-10-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField(blank=True)),
                ('genres', models.TextField(max_length=255)),
                ('original_language', models.CharField(max_length=10)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('poster_path', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
