# Generated by Django 5.1.2 on 2024-11-07 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0002_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testTask',
        ),
        migrations.AddField(
            model_name='movie',
            name='normalizedOverview',
            field=models.TextField(blank=True),
        ),
    ]
