name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Install dependencies
        run: |
          # Example for a Node.js project
          npm install

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=my_project \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://<SONARQUBE_SERVER_URL> \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
